import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./components/Header"
import { MoralisProvider } from "./components/useClient"
import { NotificationProvider } from "./components/useClient"
import SideBar from "./components/SideBar"
import {Context} from "./components/context"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <Context>
                    <MoralisProvider initializeOnMount={false}>
                        <NotificationProvider>
                            <SideBar />
                            <Header />
                            {children}
                        </NotificationProvider>
                    </MoralisProvider>
                </Context>
            </body>
        </html>
    )
}
